### ISSUE TITLE
Android build fails on macOS

### ISSUE THREAD

**Issue by YellowLabrador** [vpinball/libdmdutil#5]
The `platforms/android/arm64-v8a/external.sh` script uses `nproc` which is not a command on macOS. The top level external.sh in vpinball uses this logic

```
if [[ $(uname) == "Linux" ]]; then
   NUM_PROCS=$(nproc)
elif [[ $(uname) == "Darwin" ]]; then
   NUM_PROCS=$(sysctl -n hw.ncpu)
else
   NUM_PROCS=1
fi
```

which fixes the issue

**Comment by jsm174** [comment]
Great catch! Thank you very much! Fixed in https://github.com/vpinball/libdmdutil/commit/0a7e81f64c32b02596f11c969a07207bea48a8cc
